### ISSUE TITLE
Crear base de datos

### ISSUE THREAD

**Issue by Nain9Code** [UAX-2-DAM-Acceso-a-Datos/HibernateGrupal1-1#6]

**Comment by Medra235** [comment]
[concesionario.zip](https://github.com/UAX-2-DAM-Acceso-a-Datos/HibernateGrupal1-1/files/10002622/concesionario.zip)

**Comment by Nain9Code** [comment]
Se nos complicó pero se ha creado ya la base de datos, con vehiculo y su clave primaria y foreign en vehiculo, una clave primaria en revision.

**Comment by Medra235** [comment]
gg gente
